version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/src/learnatvcs"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/src/powerschool"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "/src/frontend/src-tauri"
    schedule:
      interval: "monthly"
