version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/src/learnatvcs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/powerschool"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/interprog-py"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/src/summarize"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/src/frontend/src-tauri"
    schedule:
      interval: "weekly"
