version = 1

test_patterns = ["test_*.py"]

exclude_patterns = [
  "poetry.lock",
  "scripts/*",
  "pnpm-lock.yaml"
]

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "1.57.0"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"
