version = 1

test_patterns = ["test_*.py"]

exclude_patterns = [
  "poetry.lock",
  "scripts/*",
  "pnpm-lock.yaml"
]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "rust"
enabled = true

  [analyzers.meta]
  msrv = "1.65.0"

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"
  max_line_length = 100

[[transformers]]
name = "rustfmt"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

# DeepSource is contradicting itself...
# [[transformers]]
# name = "black"
# enabled = true

# [[transformers]]
# name = "isort"
# enabled = true
