[package]
name = "learnatvcs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0.66"
reqwest = "^0.11.12"
tl = "^0.77"
# tl = { version = "0.7.7", features = ["simd"] }
