name: Build
on:
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [debug, release]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Setup pNPM
        uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
          cache-dependency-path: src/frontend/pnpm-lock.yaml
      - name: Setup Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install PyInstaller
        run: python -m pip install pyinstaller
      - name: Install dependencies for Tauri (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf

      - name: Load cached venv (learnatvcs)
        uses: actions/cache@v2
        with:
          path: src/learnatvcs/.venv
          key: learnatvcs-${{ runner.os }}-${{ hashFiles('src/learnatvcs/poetry.lock') }}
      - name: Load cached venv (powerschool)
        uses: actions/cache@v2
        with:
          path: src/powerschool/.venv
          key: powerschool-${{ runner.os }}-${{ hashFiles('src/powerschool/poetry.lock') }}
      - name: Install learn@vcs dependencies
        working-directory: src/learnatvcs
        run: poetry install
      - name: Install PowerSchool dependencies
        working-directory: src/powerschool
        run: poetry install
      - name: Install frontend dependencies
        working-directory: src/frontend
        run: pnpm install

      - name: Build learn@vcs
        working-directory: src/learnatvcs
        run: echo *.spec | xargs -n 1 pyinstaller
      - name: Build PowerSchool
        working-directory: src/powerschool
        run: echo *.spec | xargs -n 1 pyinstaller
      - name: Rename built binaries
        run: python scripts/rename_binaries.py

      - name: Load cached Cargo
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-${{ hashFiles('src/frontend/src-tauri/Cargo.lock') }}
      - name: Build the app (release)
        working-directory: src/frontend
        if: ${{ matrix.build_type }} == 'release'
        run: pnpm tauri build
      - name: Build the app (debug)
        working-directory: src/frontend
        if: ${{ matrix.build_type }} == 'debug'
        run: pnpm tauri build --debug

      - name: Upload artifacts (release)
        uses: actions/upload-artifact@v3
        if: ${{ matrix.build_type }} == 'release'
        with:
          name: ${{ runner.os }} ${{ runner.arch }} artifacts
          # No .app because it's pretty big and .dmg is nicer
          path: |
            src/frontend/src-tauri/target/release/bundle/*/*.dmg
            src/frontend/src-tauri/target/release/bundle/*/*.AppImage
            src/frontend/src-tauri/target/release/bundle/*/*.deb
            src/frontend/src-tauri/target/release/bundle/*/*.msi
      - name: Upload artifacts (debug)
        uses: actions/upload-artifact@v3
        if: ${{ matrix.build_type }} == 'debug'
        with:
          name: ${{ runner.os }} ${{ runner.arch }} artifacts (debug)
          path: |
            src/frontend/src-tauri/target/release/bundle/*/*.dmg
            src/frontend/src-tauri/target/release/bundle/*/*.AppImage
            src/frontend/src-tauri/target/release/bundle/*/*.deb
            src/frontend/src-tauri/target/release/bundle/*/*.msi
      # - name: Build the app
      #   uses: tauri-apps/tauri-action@v0
      #   working-directory: src/frontend
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tagName: v__VERSION__ # tauri-action replaces \_\_VERSION\_\_ with the app version
      #     releaseName: 'v__VERSION__'
      #     releaseBody: 'See the assets to download this version and install.'
      #     releaseDraft: true
      #     prerelease: false
